### ISSUE TITLE
problem when trying to create conda env

### ISSUE THREAD

**Issue by anagonda-ai** [bxuecarnegie/deepec#3]
conda env create -f environment.yml
Collecting package metadata (repodata.json): - WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0
-

**Comment by bxuecarnegie** [comment]
Can you provide some information on your environment? What system you are using, what conda version have you installed as I cannot replicate your error with just the "WARNING" message you provided.

**Comment by anagonda-ai** [comment]
conda                     23.9.0
3.10.0-514.el7.x86_64 Linux kernel version
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by bxuecarnegie** [comment]
Hi, unfortunately I don't have the exact environment with me at the moment. However, I was able to install everything on CentOS Stream release 9 with Python 3.9.19.final.0 and conda 24.4.0 running on a Virtual Machine without seeing the warnings you encountered. My guess is that you might need to update conda.
Searching online another potential error is that your conda should be configured with [libmamba solver](https://github.com/conda/conda/issues/13768#issuecomment-2385882348), use the command "conda config --set solver libmamba" to change it.
Here's the "conda info" I have.
<img width="707" alt="Screenshot 2024-11-25 023622" src="https://github.com/user-attachments/assets/f09caddd-92ab-408b-8505-e6232cfe1ecb">

**Comment by anagonda-ai** [comment]
great. managed to make it work.
thank you for you help!
